@@startuml

participant サーバー as S
participant JavaScript as J
participant ブラウザー as B

== 通常の接続 ==

B -> S: http リクエスト
activate S
S -> B: http レスポンス
deactivate S

== AJAX ==

B -> S: http リクエスト
activate S
S -> B: http レスポンス
deactivate S
activate B

group 更新
B -> J: 状態変化
activate J
J -> S: http リクエスト
activate S
S -> J: http レスポンス
deactivate S
J -> B: 画面変化
deactivate J
end

destroy B

== Web Socket ==

B -> S: http リクエスト
activate S
S -> B: http レスポンス
deactivate S
activate B

B -> J: 実行
activate J

J -> S: Web socket接続
activate S

group 送信
B -> J: 状態変化
J -> S: データ送信
end

group 受信
S -> J: データ受信
J -> B: 画面変化
end

B -> J: 終了
destroy B
J -> S: web socket 切断
deactivate J
deactivate S

@@enduml