#!/usr/bin/python3

import socket
    
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(('localhost',5900))
sock.listen(1)

while True:
    conn, addr = sock.accept()
    while True:
        data = conn.recv(1024)
        if not data:
            break
        conn.sendall(data)
    conn.close()
