#!/usr/bin/python3
import sys
import socket

BUFFER_SIZE = 1024
SEND_ADDR = ('localhost',5900)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(SEND_ADDR)

while True:
    line = sys.stdin.readline().strip()
    if line == '':
        break;
    data = line.encode('utf-8')
    len = sock.send(data)
    print('> {0}({1}:{2})'.format(line,data,len))
    if line == 'end':
        break

sock.close()
