#!/usr/bin/python3
import sys
import socket

BUFFER_SIZE = 1024
SEND_ADDR = ('localhost',5900)

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

while True:
    line = sys.stdin.readline().strip()
    data = line.encode('utf-8')
    len = sock.sendto(data, SEND_ADDR)
    print('send line: {0}\nlen: {1}'.format(data,len))
    if line == 'end':
        break

sock.close()
